### ISSUE TITLE
HTML pages not loading properly in the iframe preview since using blob URL

### ISSUE THREAD

**Issue by catalan-adobe** [adobe/helix-importer-ui#161]
Issue introduced by PR #150 

### Expected Behaviour

HTML page loaded in the iframe preview should behave the same as the page loaded in its own window.

### Actual Behaviour

Some HTML pages do not behave the same, missing content (header/footer), lazy loaded content not loading

#### Steps to Reproduce

1. Load https://business.adobe.com/au/resources/leader-in-experiences.html in its own window
=> notice the header/footer + the red banner at the bottom (loading when you scroll down)

2. Open latest version of helix importer UI and use a dummy import script to import https://business.adobe.com/au/resources/leader-in-experiences.html
=> Notice no header/footer + the bottom banner does not load on scroll

Try the same page in helix importer UI without changes from #150 and notice the page loads and behaves correctly.

#### Platform and Version

MacOS, node.js v18.15.0, helix-importer-ui v1.36.6

#### Remarks

The issue could occur on pages which react to DOM changes (ex. [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

**Comment by kptdobe** [comment]
On a side not: this still requires a CORS killer extension, otherwise the header and footer are not loaded neither.
I checked the code and the problem is that `window.location.href` is `blob:http://localhost:3001/90979e74-8a6d-47b7-9bde-25ffd736b557` and they do some regex to extract some info which is not compatible with this pattern. Checking if there is a solution.

**Comment by kptdobe** [comment]
I tried several tricks (like history push state) but no way to fix `window.location.href`: it will always be the blob url.
